"""Declarative base and shared mixins.

Each service owns a PostgreSQL schema and builds its models on a metadata object bound
to that schema. Physically the MVP shares one database instance; logically the schemas
are disjoint and no service reads another's tables, which keeps the door open to
splitting them into separate clusters without touching application code.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Final

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Deterministic constraint names so Alembic autogenerate produces stable migrations
# instead of relying on PostgreSQL's implicit naming.
NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def metadata_for_schema(schema: str) -> MetaData:
    """Return a ``MetaData`` bound to ``schema`` with the shared naming convention."""
    return MetaData(schema=schema, naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Base class for all ORM models.

    Services subclass this with their own ``metadata`` (see ``metadata_for_schema``).
    """

    metadata = metadata_for_schema("public")

    def as_dict(self) -> dict[str, Any]:
        """Return a shallow dict of column values, for logging and tests."""
        return {
            column.name: getattr(self, column.name) for column in self.__table__.columns
        }

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        primary_key = ", ".join(
            f"{column.name}={getattr(self, column.name)!r}"
            for column in self.__table__.primary_key
        )
        return f"<{type(self).__name__} {primary_key}>"


class TimestampMixin:
    """Adds server-managed ``created_at`` / ``updated_at`` columns.

    Timestamps are generated by the database (``now()``) rather than the application so
    that ordering stays consistent across replicas with skewed clocks.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
