"""Shared Alembic runner.

Each service has its own Alembic directory and version table, but the ``env.py`` logic
is identical, so it lives here. A service's ``env.py`` is a five-line call into
:func:`run_migrations`.
"""

from __future__ import annotations

from typing import Any, Literal

from alembic import context
from geoalchemy2 import alembic_helpers
from sqlalchemy import MetaData, create_engine, pool, text

from marsool_core.config import ServiceSettings
from marsool_core.db.types import StringEnum

# PostGIS creates these in the ``public`` schema. Without excluding them, every
# autogenerated migration would try to drop them.
_POSTGIS_SYSTEM_TABLES = frozenset({"spatial_ref_sys", "geography_columns", "geometry_columns"})


def _render_item(type_: str, obj: Any, autogen_context: Any) -> str | Literal[False]:
    """Render custom column types for migration scripts.

    :class:`StringEnum` needs its Python enum class at construction time, which a
    migration must not depend on — migrations have to keep working after the enum moves
    or gains variants. At the database level it is just a ``VARCHAR``.

    Everything else is delegated to GeoAlchemy2, which knows how to render its spatial
    types *and* how to add the ``import geoalchemy2`` line the rendered code needs.
    """
    if type_ == "type" and isinstance(obj, StringEnum):
        return f"sa.String(length={obj.length})"
    return alembic_helpers.render_item(type_, obj, autogen_context)


def _include_object(
    obj: Any, name: str | None, type_: str, reflected: bool, compare_to: Any
) -> bool:
    """Filter objects out of autogenerate comparisons."""
    if type_ == "table" and name in _POSTGIS_SYSTEM_TABLES:
        return False
    # Alembic's own bookkeeping table is not part of any service's domain model.
    if type_ == "table" and name == "alembic_version":
        return False
    # GeoAlchemy2's filter skips the internal columns and views PostGIS manages itself.
    return bool(alembic_helpers.include_object(obj, name, type_, reflected, compare_to))


def _build_include_name(schema: str) -> Any:
    """Restrict autogenerate to one service's schema.

    Without this, ``include_schemas=True`` makes autogenerate compare the models against
    *every* schema in the database, so one service's migration will contain DDL that drops
    another service's tables — the MVP shares a single database instance, which is exactly
    where that goes wrong.
    """

    def _include_name(name: str | None, type_: str, _parent_names: Any) -> bool:
        if type_ == "schema":
            return name == schema
        return True

    return _include_name


def run_migrations(
    *,
    metadata: MetaData,
    settings: ServiceSettings,
    schema: str,
    create_postgis: bool = False,
) -> None:
    """Run migrations for one service, in offline or online mode.

    Args:
        metadata: The service's ``MetaData`` (schema-bound).
        settings: Service settings supplying the sync DSN.
        schema: The service's PostgreSQL schema; created if absent.
        create_postgis: Whether this service needs the PostGIS extension.
    """
    if context.is_offline_mode():
        context.configure(
            url=settings.sync_database_dsn,
            literal_binds=True,
            target_metadata=metadata,
            include_schemas=True,
            include_object=_include_object,
            include_name=_build_include_name(schema),
            version_table="alembic_version",
            version_table_schema=schema,
            compare_type=True,
            compare_server_default=True,
            render_item=_render_item,
            # GeoAlchemy2's writer rewrites spatial DDL into its own operations, which
            # manage the GiST index and PostGIS metadata alongside the column.
            process_revision_directives=alembic_helpers.writer,
        )
        with context.begin_transaction():
            context.run_migrations()
        return

    engine = create_engine(settings.sync_database_dsn, poolclass=pool.NullPool)
    with engine.connect() as connection:
        if create_postgis:
            connection.execute(text("CREATE EXTENSION IF NOT EXISTS postgis"))
        connection.execute(text(f'CREATE SCHEMA IF NOT EXISTS "{schema}"'))
        connection.commit()
        context.configure(
            connection=connection,
            target_metadata=metadata,
            include_schemas=True,
            include_object=_include_object,
            include_name=_build_include_name(schema),
            version_table="alembic_version",
            version_table_schema=schema,
            compare_type=True,
            compare_server_default=True,
            render_item=_render_item,
            # GeoAlchemy2's writer rewrites spatial DDL into its own operations, which
            # manage the GiST index and PostGIS metadata alongside the column.
            process_revision_directives=alembic_helpers.writer,
        )
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()
