"""Shared Alembic runner.

Each service has its own Alembic directory and version table, but the ``env.py`` logic
is identical, so it lives here. A service's ``env.py`` is a five-line call into
:func:`run_migrations`.
"""

from __future__ import annotations

from typing import Any, Literal

from alembic import context
from sqlalchemy import MetaData, create_engine, pool, text

from marsool_core.config import ServiceSettings
from marsool_core.db.types import StringEnum


def _render_item(type_: str, obj: Any, autogen_context: Any) -> str | Literal[False]:
    """Render custom column types using plain SQLAlchemy equivalents.

    :class:`StringEnum` needs its Python enum class at construction time, which a
    migration file must not depend on — migrations have to keep working after the enum
    moves or gains variants. At the database level it is just a ``VARCHAR``, so that is
    what gets rendered.
    """
    if type_ == "type" and isinstance(obj, StringEnum):
        return f"sa.String(length={obj.length})"
    return False


def _include_object(_object: object, name: str | None, type_: str, *_args: object) -> bool:
    """Exclude PostGIS-managed objects from autogenerate.

    PostGIS creates ``spatial_ref_sys`` and internal views in the ``public`` schema;
    without this filter every autogenerated migration tries to drop them.
    """
    if type_ == "table" and name in {"spatial_ref_sys", "geography_columns", "geometry_columns"}:
        return False
    return True


def run_migrations(
    *,
    metadata: MetaData,
    settings: ServiceSettings,
    schema: str,
    create_postgis: bool = False,
) -> None:
    """Run migrations for one service, in offline or online mode.

    Args:
        metadata: The service's ``MetaData`` (schema-bound).
        settings: Service settings supplying the sync DSN.
        schema: The service's PostgreSQL schema; created if absent.
        create_postgis: Whether this service needs the PostGIS extension.
    """
    if context.is_offline_mode():
        context.configure(
            url=settings.sync_database_dsn,
            literal_binds=True,
            target_metadata=metadata,
            include_schemas=True,
            include_object=_include_object,
            version_table="alembic_version",
            version_table_schema=schema,
            compare_type=True,
            compare_server_default=True,
            render_item=_render_item,
        )
        with context.begin_transaction():
            context.run_migrations()
        return

    engine = create_engine(settings.sync_database_dsn, poolclass=pool.NullPool)
    with engine.connect() as connection:
        if create_postgis:
            connection.execute(text("CREATE EXTENSION IF NOT EXISTS postgis"))
        connection.execute(text(f'CREATE SCHEMA IF NOT EXISTS "{schema}"'))
        connection.commit()
        context.configure(
            connection=connection,
            target_metadata=metadata,
            include_schemas=True,
            include_object=_include_object,
            version_table="alembic_version",
            version_table_schema=schema,
            compare_type=True,
            compare_server_default=True,
            render_item=_render_item,
        )
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()
