"""Autogenerate filters for the shared Alembic runner.

Regression coverage for a bug that would have been destructive in production: with
``include_schemas=True`` every service compared its models against *every* schema in the
shared database, so one service's autogenerated migration contained DDL dropping another
service's tables.
"""

from __future__ import annotations

import pytest
from sqlalchemy import Integer

from marsool_core.db.migrations import (
    _build_include_name,
    _include_object,
    _render_item,
)
from marsool_core.db.types import StringEnum
from marsool_core.security.principal import Role


def test_include_name_accepts_only_the_owning_schema() -> None:
    include_name = _build_include_name("catalog")

    assert include_name("catalog", "schema", None) is True
    assert include_name("merchant", "schema", None) is False
    assert include_name("auth", "schema", None) is False
    assert include_name("identity", "schema", None) is False
    # The default (unqualified) schema is excluded too: PostGIS lives in public and is not
    # part of any service's domain model.
    assert include_name(None, "schema", None) is False


def test_include_name_does_not_filter_non_schema_objects() -> None:
    include_name = _build_include_name("catalog")
    assert include_name("menu_items", "table", None) is True
    assert include_name("price_minor", "column", None) is True


@pytest.mark.parametrize(
    "table_name",
    ["alembic_version", "spatial_ref_sys", "geography_columns", "geometry_columns"],
)
def test_infrastructure_tables_are_excluded(table_name: str) -> None:
    assert _include_object(None, table_name, "table", True, None) is False


def test_domain_tables_are_included() -> None:
    assert _include_object(None, "menu_items", "table", True, None) is True


def test_string_enum_renders_as_a_plain_varchar() -> None:
    # A migration must not depend on the Python enum class: migrations have to keep working
    # after the enum moves modules or gains variants.
    rendered = _render_item("type", StringEnum(Role, length=32), None)
    assert rendered == "sa.String(length=32)"


def test_unknown_types_are_delegated() -> None:
    # Returning False hands rendering back to Alembic and GeoAlchemy2.
    assert _render_item("type", Integer(), None) is False
